<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net7.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.Lottie</PackageId>
		<PackageVersion>6.4.0</PackageVersion>
		<AssemblyVersion>6.4.0</AssemblyVersion>
		<FileVersion>6.4.0</FileVersion>
		<Version>6.4.0</Version>
		<Title>Anjo Android Lottie SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.Lottie</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - Lottie SDK</Description>
		<PackageReleaseNotes>Lottie SDK v6.4.0</PackageReleaseNotes>
		<Copyright>Copyright (c) 2024 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, Lottie, animation</PackageTags>
		<Summary>Lottie is an animation library that renders Adobe After Effects animations natively in realtime.</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<PackageIcon>icon.png</PackageIcon>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\lottie-6.4.0.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\icon.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Square.OkIO" Version="3.6.0" />
		<PackageReference Include="Xamarin.AndroidX.AppCompat" Version="1.6.1.6" />
	</ItemGroup>
</Project>